---

- name: Include version-specific variables "{{ ansible_distribution }}"
  include_vars: "{{ ansible_distribution }}.yml"

## not supported by raspbian, https://github.com/raspberrypi/linux/issues/1352
## nok Alpine. package in edge@testing but 'Error - audit support not in kernel'
- include: auditd.yml
  when:
    - ansible_system == 'Linux'
    - not (ansible_distribution == "Debian" and ansible_architecture == "armv6l")
    - ansible_os_family != "Alpine"
